version: 2
jobs:
  build:
    docker: 
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install Nancy
          command: | 
            cd /tmp && mkdir tools && cd -
            apt-get update && apt install -y curl
            curl -s -L "https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.39/nancy-linux.amd64-v0.0.39" -o "/tmp/tools/nancy"
            chmod +x /tmp/tools/nancy
      - run:
          name: Run Nancy
          command: /tmp/tools/nancy Gopkg.lock
